// components/chat.vue
<template>
	<section id="chat">
		<div class="max-w-3xl mx-auto text-gray-900 dark:text-gray-100">
			<h3 class="text-3xl font-semibold mb-6 text-center">Chat with My Resume</h3>
			<p class="text-gray-600 dark:text-gray-300 mb-6 text-center">
				Curious if I’m a fit for your team? Ask me questions directly here.
			</p>

			<!-- Chat window -->
			<div
				class="border rounded-xl shadow p-4 h-80 overflow-y-auto mb-4
               bg-white dark:bg-gray-800
               border-gray-200 dark:border-gray-700">
				<div v-for="(msg, i) in messages" :key="i" class="mb-3">
					<!-- user -->
					<div v-if="msg.sender === 'user'" class="text-right">
						<p class="inline-block max-w-[85%] break-words
                       bg-indigo-600 text-white
                       dark:bg-indigo-500
                       px-3 py-2 rounded-lg">
							{{ msg.text }}
						</p>
					</div>
					<!-- bot -->
					<div v-else class="text-left">
						<p class="inline-block max-w-[85%] break-words
                       bg-gray-200 text-gray-900
                       dark:bg-gray-700 dark:text-gray-100
                       px-3 py-2 rounded-lg">
							{{ msg.text }}
						</p>
					</div>
				</div>

				<!-- Typing indicator -->
				<div v-if="isTyping" class="text-left">
					<p class="inline-block px-3 py-2 rounded-lg italic animate-pulse
                     bg-gray-200 text-gray-600
                     dark:bg-gray-700 dark:text-gray-300">
						Marco’s Assistant is typing…
					</p>
				</div>
			</div>

			<!-- Input -->
			<div class="flex">
				<input
					v-model="input"
					@keyup.enter="sendMessage"
					placeholder="Ask me about my experience..."
					class="flex-1 px-3 py-2 rounded-l-lg border
	                 bg-white text-gray-900 placeholder-gray-500
	                 dark:bg-gray-800 dark:text-gray-100 dark:placeholder-gray-400
	                 border-gray-300 dark:border-gray-600
	                 focus:outline-none focus:ring-2 focus:ring-indigo-500"
				/>
				<button
					@click="sendMessage"
					class="px-4 rounded-r-lg text-white
	                 bg-indigo-600 hover:bg-indigo-700
	                 dark:bg-indigo-500 dark:hover:bg-indigo-600
	                 focus:outline-none focus:ring-2 focus:ring-indigo-500"
				>
					Send
				</button>
			</div>
		</div>
	</section>
</template>

<script setup lang="ts">
	import { ref } from 'vue'
	import { useMarcoBot } from '~/composables/useMarcoBot'

	interface Message { sender: 'user' | 'bot'; text: string }

	const { getAnswer } = useMarcoBot()

	const messages = ref<Message[]>([
		{ sender: 'bot', text: "Hi, I’m Marco’s portfolio assistant! Ask me about his work experience or skills." }
	])
	const input = ref('')
	const isTyping = ref(false)

	async function sendMessage() {
		if (!input.value.trim()) return
		const userMessage = input.value
		messages.value.push({ sender: 'user', text: userMessage })
		input.value = ''
		isTyping.value = true
		try {
			const reply = await getAnswer(userMessage)
			messages.value.push({ sender: 'bot', text: reply })
		} catch (err) {
			console.error(err)
			messages.value.push({ sender: 'bot', text: 'Sorry, something went wrong while getting the answer.' })
		} finally {
			isTyping.value = false
		}
	}
</script>

// components/Chat.tsx
"use client";

import { useState } from "react";

interface Message {
	sender: "user" | "bot";
	text: string;
}

export default function Chat() {
	const [messages, setMessages] = useState<Message[]>([
		{
			sender: "bot",
			text: "Hi, I'm Marco's portfolio assistant! Ask me about his work experience or skills.",
		},
	]);
	const [input, setInput] = useState("");
	const [isTyping, setIsTyping] = useState(false);

	async function sendMessage() {
		if (!input.trim()) return;

		const userMessage = input;
		setMessages((prev) => [...prev, { sender: "user", text: userMessage }]);
		setInput("");
		setIsTyping(true);

		try {
			const response = await fetch("/api/marco-bot", {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify({ question: userMessage }),
			});

			const data = await response.json();
			setMessages((prev) => [
				...prev,
				{
					sender: "bot",
					text: data.answer || "I couldn't find an answer to that.",
				},
			]);
		} catch (err) {
			console.error(err);
			setMessages((prev) => [
				...prev,
				{
					sender: "bot",
					text: "Sorry, something went wrong while getting the answer.",
				},
			]);
		} finally {
			setIsTyping(false);
		}
	}

	return (
		<section id="chat" className="h-full flex flex-col">
			<h3 className="text-xl font-sketch mb-4 text-center text-blueprint-accent">
				Chat with My Resume
			</h3>
			<p className="text-blueprint-text-dim text-sm mb-4 text-center">
				Curious if I'm a fit? Ask me questions directly here.
			</p>

			{/* Chat window */}
			<div className="flex-1 overflow-y-auto mb-4 p-3 border-2 border-dashed border-blueprint-grid rounded bg-blueprint-bg/50">
				{messages.map((msg, i) => (
					<div
						key={i}
						className={`mb-3 ${msg.sender === "user" ? "text-right" : "text-left"}`}
					>
						<p
							className={`inline-block max-w-[85%] break-words px-3 py-2 rounded-lg text-sm font-mono ${
								msg.sender === "user"
									? "bg-blueprint-accent text-blueprint-bg"
									: "bg-blueprint-bg-light border border-dashed border-blueprint-text-dim text-blueprint-text"
							}`}
						>
							{msg.text}
						</p>
					</div>
				))}

				{isTyping && (
					<div className="text-left">
						<p className="inline-block px-3 py-2 rounded-lg italic animate-pulse bg-blueprint-bg-light text-blueprint-text-dim text-sm">
							Marco's Assistant is typing…
						</p>
					</div>
				)}
			</div>

			{/* Input */}
			<div className="flex gap-2">
				<input
					value={input}
					onChange={(e) => setInput(e.target.value)}
					onKeyUp={(e) => e.key === "Enter" && sendMessage()}
					placeholder="Ask me about my experience..."
					className="flex-1 px-3 py-2 rounded border-2 border-dashed border-blueprint-grid
                     bg-blueprint-bg text-blueprint-text placeholder-blueprint-text-dim
                     focus:outline-none focus:border-blueprint-accent focus:
                     font-mono text-sm transition-all duration-300"
				/>
				<button onClick={sendMessage} className="blueprint-btn text-sm">
					Send
				</button>
			</div>
		</section>
	);
}
